// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoHorasCompl.Data;

namespace ProjetoHorasCompl.Migrations
{
    [DbContext(typeof(ProjetoHorasComplContext))]
    partial class ProjetoHorasComplContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoHorasCompl.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AluNome");

                    b.Property<int?>("IdTurmaId");

                    b.HasKey("Id");

                    b.HasIndex("IdTurmaId");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("ProjetoHorasCompl.Models.Comprovante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CmpAluIdId");

                    b.Property<DateTime>("CmpDataFim");

                    b.Property<DateTime>("CmpDataInicio");

                    b.Property<string>("CmpDescricao");

                    b.Property<int>("CmpQtdHoras");

                    b.Property<int?>("CmpTipoComprovantesId");

                    b.HasKey("Id");

                    b.HasIndex("CmpAluIdId");

                    b.HasIndex("CmpTipoComprovantesId");

                    b.ToTable("Comprovante");
                });

            modelBuilder.Entity("ProjetoHorasCompl.Models.TipoComprovante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TipNome");

                    b.HasKey("Id");

                    b.ToTable("TipoComprovante");
                });

            modelBuilder.Entity("ProjetoHorasCompl.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TurNome");

                    b.HasKey("Id");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("ProjetoHorasCompl.Models.Aluno", b =>
                {
                    b.HasOne("ProjetoHorasCompl.Models.Turma", "IdTurma")
                        .WithMany("TurAlunos")
                        .HasForeignKey("IdTurmaId");
                });

            modelBuilder.Entity("ProjetoHorasCompl.Models.Comprovante", b =>
                {
                    b.HasOne("ProjetoHorasCompl.Models.Aluno", "CmpAluId")
                        .WithMany("Comprovantes")
                        .HasForeignKey("CmpAluIdId");

                    b.HasOne("ProjetoHorasCompl.Models.TipoComprovante", "CmpTipoComprovantes")
                        .WithMany()
                        .HasForeignKey("CmpTipoComprovantesId");
                });
#pragma warning restore 612, 618
        }
    }
}
